name: GitHub Actions Rector Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: php composer.phar install
      - run: php rector process src
