name: GitHub Actions Rector Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            extensions: mbstring, intl, ldap,fileinfo, xsl
            ini-values: post_max_size=256M, max_execution_time=180
            coverage: xdebug
            tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}
      - name: Install PHP and RUN Rector
          - uses: actions/checkout@v2
          - run: php composer.phar install
          - run: php rector process src
